version: "3"
services:
  visualizer:
    image: dockersamples/visualizer
    container_name: visualizer
    environment:
      - CTX_ROOT=/
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "8085:8080"

