version: "3"
services:
  visualizer:
    image: dockersamples/visualizer
    environment:
      - CTX_ROOT=/
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "8085:8080"
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 30s
    healthcheck:
      test: curl --fail http://127.0.0.1:8085 || exit 1
      interval: 30s
      timeout: 10s
      retries: 3

